### ISSUE TITLE
Follows migration fails on :User

### ISSUE THREAD

**Issue by rhaamo** [beta-phenylethylamine/fontina#2]
https://github.com/beta-phenylethylamine/fontina/blob/79681571f06b6c9e43cde38fe2e9855de851961f/priv/repo/migrations/20180508014113_create_follows.exs#L6-L7

It looks like I needed to change it to:
```
      add :follower_id, references(:users, on_delete: :nothing)
      add :followee_id, references(:users, on_delete: :nothing)
```

To make ecto.migrate works.

**Comment by beta-phenylethylamine** [comment]
this repo is currently considered dead, sorry.

If anyone else wants to pick it up they're welcome to, but Pixelfed and Anfora already exist and are relatively functional from my understanding

(for some more context I dropped pretty much all programming while I was going through some rough stuff and it's no longer really that worth it to be working on this imo)

for anyone who does intend to pick it up, I'd recommend basing it on pleroma rather than forking this project though, the only reason I hadn't done that was out of stubbornness
